### ISSUE TITLE
Any idea on when/if setup channel might become bidirectional?

### ISSUE THREAD

**Issue by bentito** [nvisibleinc/go-ari-proxy#36]
We have a use case that works with direct http-ari: creating a channel with ari.channels.create(). StasisStart would not have been sent at the time of this create, so no channel is available to talk on. Need to be able to initiate setup from the proxy side.

**Comment by leifmadsen** [comment]
I should probably update the README to indicate that we're not actively maintaining go-ari-proxy currently. It seems to do the needful for some people, and that's great, but unless functionality is provided via pull request there is a low likelihood of anything being added.
